name: GymFuel CI Workflow (Push to ECR)
# see github actions workflow like your own computer that is doing steps to what you want to happen
# the steps insted of writing scripts, we can find it in Github Marketplace
on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY_FRONTEND: gymfuel-frontend
  ECR_REPOSITORY_BACKEND: gymfuel-backend
  CLUSTER_NAME: gymfuel-ecs-cluster
  SERVICE_NAME_BACKEND: gymfuel-service-backend
  SERVICE_NAME_FRONTEND: gymfuel-service-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # gets my account id on aws
          IMAGE_TAG: latest
        run: |
          # 1. Build the image (the . refers to Dockerfile location)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG ./frontend

      - name: Run Trivy vulnerability scanner (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_FRONTEND }}:latest
          format: "table"
          exit-code: "1" # This fails the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Push Frontend image to ECR
        if: success() # Only runs if the Trivy scan above passed
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$IMAGE_TAG

      - name: Build, tag, and push backend image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # gets my account id on aws
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY_BACKEND }}
          IMAGE_TAG: latest
        run: |
          # 1. Build the image (the . refers to Dockerfile location)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG ./backend

      - name: Run Trivy vulnerability scanner (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:latest
          format: "table"
          exit-code: "1" # This fails the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

      - name: Push Backend image to ECR
        if: success() # Only runs if the Trivy scan above passed
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$IMAGE_TAG

      - name: Force ECS Update (Backend)
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME_BACKEND }} --force-new-deployment
      - name: Force ECS Update (Frontend)
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME_FRONTEND }} --force-new-deployment
